### ISSUE TITLE
No LICENSE in repository

### ISSUE THREAD

**Issue by Narice** [ryannhg/elm-spa-realworld#3]
Hello @ryannhg ^^
We and my team are working on an elm-spa project and would have liked to work of this repository in some parts.
The code will be modified heavily after a while but I would like the security of a license to be safe ;)
I don't really know what happens when there is no license, is it public domain or is it your code?
So yeah, if you could provide me some info or update the repository with a license, that would be fantistic! thank you!

**Comment by ryannhg** [comment]
MIT license added!
